services:
    subtitle-incrustator:
        container_name: ${PROJECT_NAME}-subtitle-incrustator
        env_file:
            - .env.local
        build:
            dockerfile: ./Dockerfile
            args:
                SERVICE_PORT: 5000
                SERVICE_NAME: subtitle-incrustator
        restart: unless-stopped
        networks:
            - api_network
        volumes:
            - ./:/app
        command: celery -A src.main.celery worker --loglevel=info --queues=api_to_subtitle_incrustator
        ports:
            - "5004:5000"

networks:
  api_network:
    name: api_network
    driver: bridge
