services:
    subtitle-merger:
        container_name: ${PROJECT_NAME}-subtitle-merger
        env_file:
            - .env.local
        build:
            dockerfile: ./Dockerfile
            args:
                SERVICE_PORT: 5000
                SERVICE_NAME: subtitle-merger
        restart: unless-stopped
        networks:
            - api_network
        volumes:
            - ./:/app
        command: celery -A src.main.celery worker --loglevel=info --queues=api_to_subtitle_merger
        ports:
            - "5002:5000"

networks:
  api_network:
    name: api_network
    driver: bridge
